routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Auth::routes();
Route::get('/home', 'HomeController@index');

Route::get('test', function (){
    $user = auth()->user();
    dd($user->quiz_results);
});


// Quiz Creation
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function (){

    // Quiz
    Route::get('quiz/new', ['as' => 'quiz.create', 'uses' => 'QuizController@create']);
    Route::post('quiz/new', ['as' => 'quiz.store', 'uses' => 'QuizController@store']);
    Route::get('{quiz}/show', ['as' => 'quiz.show', 'uses' => 'QuizController@show']);
    Route::get('{quiz}/delete', ['as' => 'quiz.destroy', 'uses' => 'QuizController@destroy']);

    // Quiz Questions
    Route::get('{quiz}/question/create', ['as' => 'question.create', 'uses' => 'QuizQuestionController@create']);
    Route::post('{quiz}/question/store', ['as' => 'question.store', 'uses' => 'QuizQuestionController@store']);
    Route::get('{quiz}/question/edit', ['as' => 'question.edit', 'uses' => 'QuizQuestionController@edit']);
    Route::post('{quiz}/question/update', ['as' => 'question.update', 'uses' => 'QuizQuestionController@update']);
    Route::get('question/{question}/destroy', ['as' => 'question.destroy', 'uses' => 'QuizQuestionController@destroy']);

    Route::get('{quiz}/{question}/show', ['as' => 'question.show', 'uses' => 'QuizQuestionController@show']);

    // Quiz Answers
    Route::post('answer/{question}/save', ['as' => 'answer.store', 'uses' => 'QuizAnswerController@store']);
});

// All Quizzes
Route::get('/', ['uses' => 'Admin\QuizController@index']);

// Take Quiz
Route::get('{quiz}/start', ['as' => 'quiz.start', 'uses' => 'TakeQuizController@start']);

// Submit Quiz
Route::post('{quiz}/submit', ['as' => 'quiz.submit', 'uses' => 'QuizResultsController@store']);

// Quiz Results
Route::get('{quiz}/results', ['as' => 'quiz.results', 'uses' => 'QuizResultsController@index']);

app/Models/Quiz.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    use Sluggable;
    protected $guarded = [];
    protected $table = 'quiz';

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function setReferenceAttribute()
    {
        return $this->attributes['reference'] = '#'.str_random(10);
    }

    public function questions()
    {
        return $this->belongsToMany(Question::class);
    }
}

app/Http/Controllers/Admin/QuizController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Question;
use App\Models\Quiz;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class QuizController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $quizzes = Quiz::all();
        return view('welcome', compact('quizzes'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.quiz.create');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $quiz = Quiz::create($request->all());
        return redirect()->route('admin.quiz.show', $quiz->slug);
    }

    /**
     * @param $quiz
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($quiz)
    {
        $quiz = Quiz::where('slug', $quiz)->get()->first();
        return view('admin.quiz.show', compact('quiz'));
    }

    /**
     * @param $quiz
     */
    public function update($quiz)
    {
        
    }

    /**
     * @param $quiz
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($quiz)
    {
        $quiz = Quiz::where('slug', $quiz)->first();
        $this->deleteQuestions($quiz);
        $quiz->delete();
        return back();
    }

    /**
     * @param $quiz
     * Grab all the quiz questions and delete them.
     */
    public function deleteQuestions($quiz)
    {
        $questions = $quiz->questions;
        foreach ($questions as $question) {
            $question->delete();
        }
    }
}

resources/views/admin/quiz/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="new-start">
        <h4>New Quiz</h4>
        <hr>
        {!! Form::open() !!}
        <div class="form-group">
            {!! Form::label('title', 'Title') !!}
            {!! Form::input('text', 'title', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('max_attempts', 'Max Attempts') !!}
            {!! Form::input('number', 'max_attempts', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('pass_percentage', 'Pass Percentage') !!}
            {!! Form::input('text', 'pass_percentage', null, ['class' => 'form-control']) !!}
        </div>

        {!! Form::hidden('reference') !!}

        <div class="form-group">
            {!! Form::submit('Submit', ['class' => 'btn btn-info']) !!}
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/quiz/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="new-start">
        <h4>All Quizzes</h4>
        <div class="bottom-10"></div>
        <table class="table">
            <thead>
                <th>Quiz Title</th>
                <th>Quiz Questions</th>
                <th>Tools</th>
            </thead>
            <tbody>
            @if(count($quizzes))
                @foreach($quizzes as $quiz)
                    <tr>
                        <td>{{ $quiz->title }}</td>
                        <td>{{ $quiz->questions->count() }}</td>
                        <td><a href="#" class="btn btn-danger">Delete</a></td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="3">You have no quizzes available.</td>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/quiz/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="new-start">
        <h4>Quiz: {{ $quiz->title }}</h4>
        <hr>
        <div class="bottom-10"></div>
        <table class="table">
            <thead>
                <th>Questions</th>
                <th>Options</th>
                <th>Correct Answer</th>
                <th>Tools</th>
            </thead>
            <tbody>
                @foreach($quiz->questions as $question)
                    <tr>
                        <td><a href="{{ route('admin.question.show', [$quiz->slug, $question->slug]) }}">{{ $question->title }}</a></td>
                        <td>{{ count($question->options) }}</td>
                        <td>
                            @if(count($question->answers) === 0)
                                <a href="{{ route('admin.question.show',[$quiz->slug, $question->slug]) }}">Add Answer</a>
                            @else
                                {{ \App\Models\Option::find($question->answers->first()->option_id)->title }}
                            @endif
                        </td>
                        <td><a href="{{ route('admin.question.destroy', $question->slug) }}">Delete Question</a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <a href="/" class="btn btn-success">Home</a>
        <a href="{{ route('admin.question.create', $quiz->slug) }}" class="btn btn-info">Add Questions</a>
    </div>
@endsection