routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Auth::routes();
Route::get('/home', 'HomeController@index');

Route::get('test', function (){
    $user = auth()->user();
    dd($user->quiz_results);
});


// Quiz Creation
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function (){

    // Quiz
    Route::get('quiz/new', ['as' => 'quiz.create', 'uses' => 'QuizController@create']);
    Route::post('quiz/new', ['as' => 'quiz.store', 'uses' => 'QuizController@store']);
    Route::get('{quiz}/show', ['as' => 'quiz.show', 'uses' => 'QuizController@show']);
    Route::get('{quiz}/delete', ['as' => 'quiz.destroy', 'uses' => 'QuizController@destroy']);

    // Quiz Questions
    Route::get('{quiz}/question/create', ['as' => 'question.create', 'uses' => 'QuizQuestionController@create']);
    Route::post('{quiz}/question/store', ['as' => 'question.store', 'uses' => 'QuizQuestionController@store']);
    Route::get('{quiz}/question/edit', ['as' => 'question.edit', 'uses' => 'QuizQuestionController@edit']);
    Route::post('{quiz}/question/update', ['as' => 'question.update', 'uses' => 'QuizQuestionController@update']);
    Route::get('question/{question}/destroy', ['as' => 'question.destroy', 'uses' => 'QuizQuestionController@destroy']);

    Route::get('{quiz}/{question}/show', ['as' => 'question.show', 'uses' => 'QuizQuestionController@show']);

    // Quiz Answers
    Route::post('answer/{question}/save', ['as' => 'answer.store', 'uses' => 'QuizAnswerController@store']);
});

// All Quizzes
Route::get('/', ['uses' => 'Admin\QuizController@index']);

// Take Quiz
Route::get('{quiz}/start', ['as' => 'quiz.start', 'uses' => 'TakeQuizController@start']);

// Submit Quiz
Route::post('{quiz}/submit', ['as' => 'quiz.submit', 'uses' => 'QuizResultsController@store']);

// Quiz Results
Route::get('{quiz}/results', ['as' => 'quiz.results', 'uses' => 'QuizResultsController@index']);

app/Models/Question.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use Sluggable;
    protected $table = 'questions';
    protected $guarded = [];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function quiz()
    {
        return $this->belongsToMany(Quiz::class);
    }

    public function options()
    {
        return $this->hasMany(Option::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function answerIsSet()
    {
        $count = $this->answers()->count();
        if ($count > 0){
            return true;
        }else{
            return false;
        }
    }

}

resources/views/admin/question/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="new-start">
        <h4>Quiz: {{ $quiz->title }}</h4>
        <hr>

        {!! Form::open(['method' => 'post', 'route' => ['admin.question.store', $quiz->slug]]) !!}
        <div class="form-group">
            {!! Form::label('title', 'Question Title') !!}
            {!! Form::input('text', 'title', null, ['class' => 'form-control']) !!}
        </div>

        <hr>
        <div class="question-options"></div>
        <div class="add-question-option btn btn-info">Add New Option</div>
        <hr>

        <div class="form-group">
            <a href="{{ route('admin.quiz.show', $quiz->slug) }}" class="btn btn-info">Back to quiz</a>
            {!! Form::submit('Submit', ['class' => 'btn btn-info']) !!}
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/question/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="new-start">
        <h4>Question: {{ $question->title }}</h4>
        <div class="bottom-10"></div>

        @if($question->answerIsSet())
            <table class="table">
                <thead>
                    <th>Answer Option</th>
                    <th>Correct</th>
                </thead>
                <tbody>
                    @foreach($question->options as $option)
                        <tr>
                            <td>{{ $option->title }}</td>
                            <td>
                                @if($option->isCorrect())
                                    Correct
                                @else
                                    Incorrect
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <a href="{{ route('admin.quiz.show', $quiz->slug) }}" class="btn btn-info">Back to Quiz</a>
        @else
            <p>Please select your answers for this question</p>
            <hr>
            {!! Form::open(['method' => 'post', 'route' => [ 'admin.answer.store', $question->slug ]]) !!}
                @foreach($question->options as $option)
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" class="" name="option[]" value="{{ $option->id }}">
                            {{ $option->title }}
                        </label>
                    </div>
                @endforeach
            <hr>
                {!! Form::submit('Save Changes', ['class' => 'btn btn-info']) !!}
            {!! Form::close() !!}
        @endif
    </div>
@endsection